export const NOTIFICATION_TYPES = {
	WELCOME: "WELCOME",
	APP_UPDATE: "APP_UPDATE",
	JOURNAL_DAILY_REMINDER: "JOURNAL_DAILY_REMINDER",
	CALENDAR_EVENT_REMINDER: "CALENDAR_EVENT_REMINDER",
	GOAL_CHECKIN_REMINDER: "GOAL_CHECKIN_REMINDER",
	GOAL_DEADLINE_APPROACHING: "GOAL_DEADLINE_APPROACHING",
	MEMO_REMINDER: "MEMO_REMINDER",
	DAILY_BRIEFING: "DAILY_BRIEFING",
} as const;

export type { NotificationTarget, NotificationType } from "@repo/database";
